### ISSUE TITLE
support for loading dotenv vault

### ISSUE THREAD

**Issue by BluestockLabs** [nestjs/config#1697]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I recently made the switch from using just dotenv to using [dotenv-vault](https://github.com/dotenv-org/dotenv-vault). Most things stay the same except it allows you to *sync* dotenv files securely and provides central management for it.

I was just about to deploy an app when I noticed it wasn't reading the env files after I had provided the DOTENV_KEY. I did a little digging around and it doesn't seem like this `config` module from nest supports that.

### Describe the solution you'd like

I'd like support for loading environment variables from encrypted `.env.vault` files after providing the DOTENV_KEY.

### What is the motivation / use case for changing the behavior?

Though dotenv-vault is relatively new compared to dotenv, I believe adoption is growing and sooner or later Nestjs users will request for support for this feature (I'm actually a bit surprised that no one as asked about this yet)

**Comment by BluestockLabs** [comment]
Sorry, I was logged in to a client's account. @drvnprgrmr is the actual author of this issue.

**Comment by drvnprgrmr** [comment]
Yeah. Mistake on my part.

**Comment by micalevisk** [comment]
can you please share the exact steps (or a repository) that reproduces this potential limitation of `@nestjs/config`? I want to make sure that this is not a misconfiguration on the consumer side.

**Comment by drvnprgrmr** [comment]
@micalevisk yes all those work. The issue is that @nestjs/config doesn't automatically decrypt the dotenv vault based on the environment variable: `DOTENV_KEY`.

I believe that's the whole point of the vault. That way you don't have to always update your environment variables on whatever server you're using. Just commit the vault and push and your environment is reflected.

**Comment by kamilmysliwiec** [comment]
> The issue is that @nestjs/config doesn't automatically decrypt the dotenv vault based on the environment variable: DOTENV_KEY.

Does `dotenv` alone automatically decrypt the dotenv vault?

**Comment by micalevisk** [comment]
yes, like this: https://github.com/dotenv-org/examples/blob/master/usage/dotenv-vault-custom-target/index.js

![image](https://github.com/nestjs/config/assets/13461315/0af2cc64-0326-4ff6-9391-24b88a334b5a)

note that you can have an env. var called `DOTENV_KEY` instead of supplying it to `dotenv.config()`

not sure how we could support it on `@nestjs/config` tho

**Comment by drvnprgrmr** [comment]
@kamilmysliwiec Yes it does.
<img width="902" alt="image" src="https://github.com/nestjs/config/assets/67306305/d111ca85-a89a-4da8-a924-3fc86d94b813">

**Comment by kamilmysliwiec** [comment]
It sounds like dotenv-vault is going to be deprecated in favor of dotenvx anyway 

![image](https://github.com/user-attachments/assets/8774e9ac-7bac-4619-beff-9e4573583379)

https://github.com/dotenvx/dotenvx?tab=readme-ov-file#what-happened-to-the-envvault-file

**Comment by drvnprgrmr** [comment]
> It sounds like dotenv-vault is going to be deprecated in favor of dotenvx anyway 
> 
> ![image](https://github.com/user-attachments/assets/8774e9ac-7bac-4619-beff-9e4573583379)
> 
> https://github.com/dotenvx/dotenvx?tab=readme-ov-file#what-happened-to-the-envvault-file

Okay thanks for that. I didn't know.
