### ISSUE TITLE
Add dotenv-expand support so that env vars can contain other env vars

### ISSUE THREAD

**Issue by msheakoski** [nestjs/config#25]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

I just noticed that you recently created a config package to replace the config module guide that was in the docs. I would love to replace my custom config module with this one, but one really useful feature I added which this config package is missing is variable expansion with [dotenv-expand](https://github.com/motdotla/dotenv-expand) in order to have env files [like this](https://github.com/motdotla/dotenv-expand/blob/master/test/.env).

Here is a snippet of code that I used to implement it as an example:
```typescript
import expand from "dotenv-expand"
import fs from "fs"
import { Injectable } from "@nestjs/common"
import { parse } from "dotenv"

@Injectable()
export class ConfigService {
  private readonly data: Record<string, string | undefined> = {}

  constructor(envFilePath: string) {
    if (fs.existsSync(envFilePath)) {
      const parsedVars = parse(fs.readFileSync(envFilePath))
      const expandedVars = expand({ parsed: parsedVars }).parsed
      if (!expandedVars) {
        throw new Error(
          `A problem was encountered while parsing "${envFilePath}".`,
        )
      }
      this.data = expandedVars
    }
    // Environment variables have higher priority than envFile.
    Object.assign(this.data, process.env)
  }

  get(key: string): string | undefined {
    return this.data[key]
  }
}
```

**Comment by kamilmysliwiec** [comment]
We can add this feature under a flag (when enabled). Would you like to create a PR?

**Comment by msheakoski** [comment]
I will not have much time in the next 2 weeks to work on it, but I would be glad to submit a PR when I have availability if nobody else gets to it first.

**Comment by prateekkathal** [comment]
I think I'll be able to get my hands on this today itself. Will create a PR soon.

**Comment by prateekkathal** [comment]
@kamilmysliwiec I was working on this and just ran `npm run test:integration` and it seems all tests are failing due to some changes made in @hapi/joi (v17)

https://d.pr/i/ai0yIB
![image](https://user-images.githubusercontent.com/7609893/71922793-a3e89300-3159-11ea-8632-b31b32bb15bd.png)

[This is the line](https://github.com/hapijs/joi/blob/master/lib/errors.js#L246) that is causing the failure.

Not sure how CircleCI tests are running fine.

**Comment by kamilmysliwiec** [comment]
@prateekkathal it looks like a Joi issue - https://github.com/hapijs/joi/issues/2271

**Comment by prateekkathal** [comment]
@kamilmysliwiec As per hapijs/joi#2266, it looks like we'll have to change the documentation and ask them to run on `Node v12`.

Do you think we should update the [hapijs/joi](https://github.com/hapijs/joi) version for this package because of that though? 

Let me know your thoughts. I'll update my node version and make a PR for this and update the documentation on [nestjs/docs.nestjs.com](https://github.com/nestjs/docs.nestjs.com).

**Comment by kamilmysliwiec** [comment]
Added in 0.1.0. Thank you @prateekkathal!
