### ISSUE TITLE
Passing validationOptions: { allowUnknown: false } causes errors for env values outside the schema

### ISSUE THREAD

**Issue by jtlindsey** [nestjs/config#618]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
Passing `validationOptions: { allowUnknown: false }` causes errors for environment values not in `.env`

## Expected behavior
Only throw error if environment value is in `.env` file but not in `validationSchema`

## Minimal reproduction of the problem with instructions

`app.module.ts`
```
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { ConfigModule } from '@nestjs/config';
import * as Joi from 'joi';

@Module({
  imports: [
    ConfigModule.forRoot({
      validationSchema: Joi.object({
        NODE_ENV: Joi.string()
          .valid('development', 'production', 'test', 'provision')
          .default('development'),
        PORT: Joi.number().default(3000),
      }),
      validationOptions: {
        allowUnknown: false,
      },
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}

```

`.env`
```
NODE_ENV=development
PORT=3001
```

## What is the motivation / use case for changing the behavior?
To prevent unnecessarily having to list ~227 default environment variables in the schema in addition to the ones in your `.env`.

## Environment

<pre><code>
Nest version: 8.0.2

 
For Tooling issues:
- Node version: 14.17.3
- Platform:  Mac

Others:

</code></pre>
Related
https://github.com/nestjs/config/pull/15

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by jtlindsey** [comment]
Yes, if it is a bug and I figure out how to fix it. Based on it's current setup I don't imagine anyone is using `allowUnknown: false` because they would have to specify (in the schema) the other 227+ default environment variables that they may not be interacting with. Is this a bug or is this intended behavior?

`process.env` is hardcoded [here](https://github.com/nestjs/config/blob/0a38397a1a9f7fe7c5e2bd670b8e355d1ef566e4/lib/config.module.ts#L46). To prevent affecting functionality in other code interacting with `config`, it seems a good option would be for the user to pass a validation file [here](https://github.com/nestjs/config/blob/0a38397a1a9f7fe7c5e2bd670b8e355d1ef566e4/lib/config.module.ts#L58) and have it default to `.env`. Does that make any sense or is it better to make a change on `loadEnvFile` and try to preserve the behavior of when users add custom environment files other than `.env`? I'm not familiar with `nestjs` codebase yet. My first `nest new project-name` was the day I opened the ticket.

**Comment by prateekkathal** [comment]
@jtlindsey Yes, I realized the purpose of `allowUnknown` was only relevant to singular `ConfigModule` settings.

If you have multiple, obviously others will be unknown for it. So I stopped using it.

IMO, we should possibly store an array of all the validated env variables from all the different places where we used `ConfigModule` and then check for there is still an _unknown_ variable inside the `.env`. But again, this setting must only correspond to the global module rather than all modules.

Not sure if I make sense here? 😅  CC: @kamilmysliwiec

**Comment by kamilmysliwiec** [comment]
What if someone wants to validate the actual env variables (and their presence), not only those specified in the `.env` file?

**Comment by prateekkathal** [comment]
> What if someone wants to validate the actual env variables (and their presence), not only those specified in the `.env` file?

Is this directed to me? What do you mean not only those in `.env`? 

According to me if let's say we have 2 modules `SessionConfigModule` (eg `SESSION_TTL`) & `CacheConfigModule` (eg `CACHE_TTL`), setting `{ allowUnknown: false }` in either of the modules should not throw any errors because both modules have the variables defined & validation added for them.

If let's say I add another variable `QUEUE_LIMIT`, then `allowUnknown` should throw an error, saying unknowns are not allowed.

Currently, setting `{ allowUnknown: false }` in either of the modules will throw an error, which isn't right I feel. 

So as suggested in my previous message, if we are able to create a list of all the defined variables & validate all ([run this](https://github.com/nestjs/config/blob/master/lib/config.module.ts#L58)) in one go instead of separately for each module, that should resolve the issue I think.

**Comment by kamilmysliwiec** [comment]
> According to me if let's say we have 2 modules SessionConfigModule (eg SESSION_TTL) & CacheConfigModule (eg CACHE_TTL), setting { allowUnknown: false } in either of the modules should not throw any errors because both modules have the variables defined & validation added for them.

Not sure what you mean. `ConfigModule#forRoot` should never be called more than once within a single application.

**Comment by prateekkathal** [comment]
> > According to me if let's say we have 2 modules SessionConfigModule (eg SESSION_TTL) & CacheConfigModule (eg CACHE_TTL), setting { allowUnknown: false } in either of the modules should not throw any errors because both modules have the variables defined & validation added for them.
> 
> Not sure what you mean. `ConfigModule#forRoot` should never be called more than once within a single application.

@kamilmysliwiec How do you propose we allow creation of multiple config modules? For eg: `AppConfigService` or `CacheConfigService`?

`AppConfigService` will only support env variables prefixed with `APP_` & `CacheConfigService` will only support env variables prefixed with `CACHE_`?

**Comment by kamilmysliwiec** [comment]
> @kamilmysliwiec How do you propose we allow creation of multiple config modules?

Create wrapper services that use the built-in `ConfigService` under the hood.

**Comment by prateekkathal** [comment]
@kamilmysliwiec Is this considered a bad way of doing things? 

![image](https://user-images.githubusercontent.com/7609893/129747993-b2ceb802-f289-430a-93e1-79aef54e31c7.png)
![image](https://user-images.githubusercontent.com/7609893/129748090-83682ff4-5ffa-4d39-9680-acfaf9d03beb.png)

This helps me `import: [CacheConfigModule]` or `import: [AppConfigModule]` only where it is is required, rather than globally importing the `ConfigModule` inside `AppModule`.

**Comment by kamilmysliwiec** [comment]
> Is this considered a bad way of doing things?

Yes. There are 2 issues here:
- you should never import `ConfigModule#forRoot()` twice (as the name suggests, "forRoot")
- you should never define `ConfigService` (from `@nestjs/config`) as a provider

**Comment by prateekkathal** [comment]
@kamilmysliwiec Understood. Thanks.

**Comment by rteano** [comment]
> What if someone wants to validate the actual env variables (and their presence), not only those specified in the `.env` file?

@kamilmysliwiec I am currently experiencing this issue and so I opted not to use the validation option anymore. It would be nice if we can have a flag that tells the config module to do a strict validation only to `env` files or with `.env` by default and add additional validation with env vars not included in any `env` file/s if a user insist as you mentioned to validate an actual env var not included in any `env` file/s.

**Comment by liaoliaots** [comment]
@jtlindsey 
_This is expected behavior, not a bug._

**Firstly**, `joi` is a data validator for JavaScript, not only for **nestjs**, `@nestjs/config` is just a usage scene.

**Secondly**, the `validationOptions` option receives **options** for the `validate` method of the `joi` library. If `validationOptions` is not provided, `@nestjs/config` will return `{abortEarly: false,allowUnknown: true}`.

- For the `allowUnknown` option, it defaults to `true` because the `joi` library's `allowUnknown` option defaults to `false` and process.env has many environment variables.
- For the `abortEarly` option, it defaults to `false` because the `joi` library's `abortEarly` option defaults to `true` and to see which environment variables do not pass validation.

details:
https://github.com/nestjs/config/blob/master/lib/config.module.ts#L198
https://joi.dev/api/?v=17.4.2#anyvalidatevalue-options
