### ISSUE TITLE
Type error: `No overload matches this call...` when using v1.1.2 along with `@nestjs/common` v8.2.3

### ISSUE THREAD

**Issue by micalevisk** [nestjs/config#749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm not sure where to report this, tbh. Looks like a regression.

After this commit https://github.com/nestjs/nest/commit/97f9348ce59c8d56add02ee10ba4759884779682#diff-e617c1985a04f0fb52a07057cd1a5d7b2d2bdbc8b1273853dcf5018740cb705a (`@nestjs/common@8.2.3`), I'm getting the following TypeScript compiler error while [using `ConfigService` as the doc shows](https://docs.nestjs.com/techniques/configuration#using-the-configservice):

```
  No overload matches this call.
  Overload 1 of 4, '(propertyPath: any, options: ConfigGetOptions): any', gave the following error.
    Argument of type 'number' is not assignable to parameter of type 'ConfigGetOptions'.
  Overload 2 of 4, '(propertyPath: never, defaultValue: number): number', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'never'.ts(2769)
```

when we use `app.get(ConfigService)` because the type of this is  
`ConfigService<unknown, boolean>`

To circumvent that, we can do `app.get<ConfigService>(ConfigService)`, to make it return  
`ConfigService<Record<string, unknown>, false>` instead  
but this isn't ideal

### Minimum reproduction code

https://gitlab.com/micalevisk/nestjs-config-issue-749

### Steps to reproduce

follow the `README.md` file above

### Expected behavior

behave just like it behaves with `@nestjs/config@8.2.2`. Check out the branch `working` on my repo above

### Package version

1.1.2

### NestJS version

8.2.3

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

![image](https://user-images.githubusercontent.com/13461315/143096846-bfad7abd-7ef1-4382-9823-d9d0c94ff288.png)

**Comment by kamilmysliwiec** [comment]
So this one was tricky.

`app.get(ConfigService)` should return `ConfigService<Record<string, unknown>, false>` as these are the default type arguments. Instead, `InstanceType<ConfigService>` returns `ConfigService<unknown, boolean>` (when used as in the example below) as it seems that TypeScript fallbacks to the `extends` constraints when inferring types.

Example:
```typescript
interface Type<T = any> extends Function {
  new (...args: any[]): T;
}

class InferIssue<T = Record<string, unknown>, R extends boolean = false> {}

function get<TInput extends Type>(cls: TInput): InstanceType<TInput> {
  return {} as any;
}

// this works as expected
// == type InferIssueInstance = InferIssue<Record<string, unknown>, false> 👈 
type InferIssueInstance = InstanceType<Type<InferIssue>>;

// this doesn't work as expected
// function get<typeof InferIssue>(cls: typeof InferIssue): InferIssue<unknown, boolean> 👈 
get(InferIssue);
```

That means we'd have to add `extends Record<string, unknown` constraint to the `ConfigService` type argument but as @micalevisk you pointed out, interfaces don't extend `Record` type https://github.com/microsoft/TypeScript/issues/42825#issuecomment-780160383 so that would be even a bigger breaking change.

Fixed in this commit https://github.com/nestjs/config/commit/eec4653e8546c37f42135409c1ae78b31e76f04e
