### ISSUE TITLE
Why Joi instead of class-validator

### ISSUE THREAD

**Issue by viczam** [nestjs/config#9]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
Why using joi instead of class-validator, as the latter is more like a standard package for nest.

## Expected behavior
Allow using class-validator.

**Comment by viczam** [comment]
Actually I've noticed there's no hard dependency on Joi, this way as long as `options.validationSchema.validate` is a function, that will do it.

**Comment by deemaagog** [comment]
@viczam Did you figure out how to use class-validator?

**Comment by kamilmysliwiec** [comment]
We used Joi because there is no reason to use `class-validator`. You'll always interact with the configuration using `ConfigService` either way regardless of whether there is an instance of a class decorated with `class-validator` or not. Using `class-validator` would force everyone to define a class even if they don't want to validate/verify all the parameters. Defining a schema, in this case, is easier and more straightforward.
